---
- hosts: localhost
  vars:
    project_root: "{{ playbook_dir }}/../../../.."
    kubelet_location: "https://dl.k8s.io/v1.16.2/kubernetes-node-windows-amd64.tar.gz"
    wmcb_exe: "wmcb.exe"

  tasks:
    - name: Gather required files
      block:

        - name: Create directory to store files to be used later
          tempfile:
            state: directory
          register: tmp_dir

        - name: Build WMCB
          make:
            target: build
            chdir: "{{ project_root }}"

        - name: Move WMCB to temporary directory
          command: mv "{{ project_root }}/{{ wmcb_exe }}" "{{ tmp_dir.path }}/{{ wmcb_exe }}"

        - name: Download Windows node kubelet
          get_url:
            url: "{{ kubelet_location }}"
            dest: "{{ tmp_dir.path }}/kube.tar.gz"

        - name: Extract kubelet
          unarchive:
            src: "{{ tmp_dir.path }}/kube.tar.gz"
            dest: "{{ tmp_dir.path }}"

        - name: Grab kubelet from extracted directories
          copy:
            src: "{{ tmp_dir.path }}/kubernetes/node/bin/kubelet.exe"
            dest: "{{ tmp_dir.path }}/kubelet.exe"

- hosts: win
  vars:
    tmp_path: "{{ playbook_dir }}/tmp"

  tasks:
    - name: Create temporary directory
      win_tempfile:
        state: directory
      register: win_temp_dir
    - name: Copy required files to Windows host
      win_copy:
        src: "{{ hostvars['localhost']['tmp_dir']['path'] }}/"
        dest: "{{ win_temp_dir.path }}"

    - name: Get ignition file
      win_get_url:
        url: "https://api-int.{{ cluster_address }}:22623/config/worker"
        dest: "{{ win_temp_dir.path }}\\worker.ign"
        validate_certs: no

    - name: Run bootstrapper
      win_shell: "{{ win_temp_dir.path }}\\wmcb.exe initialize-kubelet --ignition-file {{ win_temp_dir.path }}\\worker.ign --kubelet-path {{ win_temp_dir.path }}\\kubelet.exe"
      register: bootstrap_out

    - name: Check if bootstrap was successful
      fail:
        msg: "Bootstrapper error"
      when: '"Bootstrapping completed successfully" not in bootstrap_out.stderr'

    - name: Initial wait for bootstrap CSR
      pause:
        seconds: 60

    - name: Check for bootstrap CSR
      delegate_to: localhost
      shell: "oc get csr | awk '/system:serviceaccount:openshift-machine-config-operator:node-bootstrapper/ && /Pending/ {print $1}'"
      register: bootstrap_csrs
      until: bootstrap_csrs.stdout != ""
      retries: 2
      delay: 60

    - name: Approve pending bootstrap CSRs
      delegate_to: localhost
      shell: "oc adm certificate approve {{ item }}"
      with_items: "{{ bootstrap_csrs.stdout_lines }}"

    - name: Initial wait for node CSR
      pause:
        seconds: 60

    - name: Wait for node CSR
      delegate_to: localhost
      shell: "oc get csr | awk '/system:node:/ && /Pending/ {print $1}'"
      register: node_csrs
      until: node_csrs.stdout != ""
      retries: 2
      delay: 60

    - name: Approve pending node CSRs
      delegate_to: localhost
      shell: "oc adm certificate approve {{ item }}"
      with_items: "{{ node_csrs.stdout_lines }}"

    # Get the bootstrapped windows node name. We're using the IP address of the Windows VM created
    # in the inventory file and if the node has multiple internal IP's or external IP's it may not work well.
    # TODO: Move this to a more deterministic way of identifying the node we just bootstrapped
    - name: Get bootstrapped node name
      delegate_to: localhost
      shell: "oc get node -o wide |awk '/{{ inventory_hostname }}/ {print $1}'"
      register: node_name
      until: node_name.stdout != ""
      retries: 3
      delay: 5

    # Check if worker label is already applied to the Windows nodes bootstrapped via WMCB
    # We should always get a single node that we've bootstrapped recently, if not skip this
    # step
    - name: Check if worker label is already applied to the Windows nodes bootstrapped via WMCB
      delegate_to: localhost
      shell: "oc get node {{ node_name.stdout_lines[0] }} -o yaml | grep -i node-role.kubernetes.io/worker"
      ignore_errors: yes
      register: checklabels
      when: node_name.stdout_lines | length == 1

    # Apply worker label to the Windows nodes bootstrapped via WMCB
    - name: Label the Windows node that was just bootstrapped with worker labels
      delegate_to: localhost
      shell: "oc label node {{ node_name.stdout_lines[0] }} node-role.kubernetes.io/worker="
      when: node_name.stdout_lines | length == 1 and checklabels.rc == 1
