---
- name: Create temporary directory on windows host
  win_tempfile:
    state: directory
  register: tempdir_win
  # Ruby Devkit installs Ruby + MSYS2 packages and adds Ruby executables to PATH
  # Enable installation of RubyGems
  # Ruby version < 2.6 and >= 2.4, 64 bit
- name: Fetch ruby devkit exe
  win_get_url:
    url: "{{ ruby_fetch_url }}"
    dest: "{{ tempdir_win.path }}\\"
    # Requires Ansible version 2.9
    follow_redirects: all
  register: ruby_devkit
- name: Check install path
  win_stat:
    path: "{{ install_dir }}"
  when: install_dir is defined
  register: install_dir_exists
- name: Install ruby to particular directory
  win_shell: "{{ ruby_devkit.dest }} /VERYSILENT /SUPPRESSMSGBOXES /DIR={{ install_dir }}"
  when: install_dir is defined and install_dir_exists.stat.exists
- name: Install ruby
  win_shell: "{{ ruby_devkit.dest }} /VERYSILENT /SUPPRESSMSGBOXES"
  when: install_dir is not defined or
        (install_dir_exists is defined and install_dir_exists.stat.exists==false)
- name: Check ruby installed
  win_shell: "ruby --version"
  # Install Fluentd RubyGem. Fluentd version 1.5.1 or higher
- name: Install fluentd (version specific)
  win_shell: gem install fluentd -v '~> {{ fluentd_version }}'
  when: fluentd_version is defined
- name: Install fluentd
  win_shell: gem install fluentd
  when: fluentd_version is not defined
- name: Delete temporary directory on windows host
  win_file:
    path: "{{ tempdir_win.path }}"
    state: absent
  when: tempdir_win.path is defined
