---
- hosts: win
  tasks:
  - name: Logging | Install Fluentd
    include_tasks: install_fluentd.yml

  - name: Logging | Install fluentd plugins
    include_tasks: install_plugins.yml

  #- name: Logging | Configure
  #  include_tasks: configure.yml
